services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AwesomePass_1234
    restart: always
    volumes:
      - ./volumes/sql_data:/var/opt/mssql

  companyemployees:
    image: ezspace/comp:runtime
    container_name: companyemployees
    depends_on:
      - db
    build:
      context: .
    ports:
      - "80:5000"
      - "443:5001"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companyemployees.pfx
      - SECRET=MyVerySecureAndLongSecretKey123456
    volumes:
      - ./volumes/serts:/https/